spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/max_zvaryh_db_lab3?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
=======
    url: jdbc:mysql://localhost:3306/max_zvaryh_db_lab3?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=falsejdbc:mysql://localhost:3306/max_zvaryh_db_lab3?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
>>>>>>> 2efcb3fe1b1d31457062ccb5f02d82e928631645
    username: Masyanya
    password: Max0993319943
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      dialect: org.hibernate.dialect.MySQL57Dialect
      ddl-auto: update
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
